### ISSUE TITLE
Products sorting by name affected by HTML entities

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-rest-api#146]
In the Woo mobile app, we are sorting the product list by `name`. HTML tags in the product name can affect the ordering. For example, my product <em>Cool</em> Beanie &amp; More! appears at the top of the product list instead of being ordered by the first letter “c” in the name:

<img width="1085" alt="Screenshot 2020-02-26 at 12 29 50 PM" src="https://user-images.githubusercontent.com/22608780/75320938-c794a380-5895-11ea-8c2c-1dc82694034d.png">

<img width="300" src="https://user-images.githubusercontent.com/22608780/75320977-d7ac8300-5895-11ea-910a-33808b9d346e.png">

**Comment by vedanshujain** [comment]
Unfortunately, to ignore the HTML entity here means we won't be able to use the SQL's sorting feature which will be prohibitively slow to implement.

That said, a workaround is to order by `slug` instead of title, which already strips HTML entities before saving. I am closing because of suggested workaround, and inability to implement without paying heavy performance penalties.
