### ISSUE TITLE
Custom taxonomy not showing on API request

### ISSUE THREAD

**Issue by fabianwurk** [woocommerce/woocommerce-rest-api#149]
I have a custom taxonomy called 'brand' created for WooCommerce which does appear in the backend fine, but when I do a GET request via API call it doesn't show the taxonomy in the json response.

I've added this when I've registered the custom tax:

`		'show_in_rest'               => true,
		'rest_base'                  => 'brand',
		'rest_controller_class'      => 'WC_REST_Products_Controller',
` 

Any idea why this may be happening?

Thanks.

**Comment by vedanshujain** [comment]
I was able to register a taxonomy as you suggest in the code and see the API reponse on it after removing the `'rest_controller_class' => 'WC_REST_Products_Controller'` argument. Note that using WC_REST_Products_Controller won't do anything on its own, it seems like you want to use something like [categories](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-categories).

I am closing this issue because we have been late in responding so it's likely that you have moved on or solved the problem by yourself already. Feel free to comment back if that's not the case.
