### ISSUE TITLE
woocommerce_rest_prepare_X_object cant remove single item

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce-rest-api#151]
when we want to remove single item using 'woocommerce_rest_prepare_X_object' hook. the end result will be empty array..

Its because of this file:
 woocommerce-rest-api/src/Controllers/Version3/class-wc-rest-crud-controller.php (line 363)

it should do a is_empty() check before adding it to $objects[]
if not, the end result will be an empty array of item

**Comment by vedanshujain** [comment]
`woocommerce_rest_prepare_X_object` is only for modifying the object response and cannot handle the deletion of the object. This is because by the time we reach this filter, other calculations like total pages, the number of objects on the current page, etc are already done and cannot be modified. Adding an `is_empty` check will cause these calculations to be incorrect.

If you'd like to exclude an item, the correct way would be to add an `exclude` param in the API call or add filter in the before the resource is being queried.
