### ISSUE TITLE
POST /orders doesn't check stock

### ISSUE THREAD

**Issue by yepMad** [woocommerce/woocommerce-rest-api#166]
Let's say that two people place the same order and one of them runs out of stock, while the other is still finalizing the purchase.

**WooCommerce.postAsync ('orders /')** does not check whether the stock is greater than zero before posting the order. Getting -1 in the Wordpress panel.

**Comment by vedanshujain** [comment]
Currently, we do not have a checkout API, and the orders API intentionally does not check before posting the order because it's usually used by backoffice. If you are using it to power frontend and creating orders for customers, then I'd recommend that you use `woocommerce_rest_pre_insert_order_object` (search for `woocommerce_rest_pre_insert_{$this->post_type}_object` in codebase for arguments) and perform extra checks you need there. 
I am closing this issue but feel free to write back if you want to discuss more.
