### ISSUE TITLE
Rest Api unable to authenticate

### ISSUE THREAD

**Issue by testapi60** [woocommerce/woocommerce-rest-api#193]
<img width="824" alt="Screenshot 2020-05-18 at 7 43 07 PM" src="https://user-images.githubusercontent.com/65539040/82223239-0770a180-9940-11ea-8346-46297b3572f9.png">
I have used http and https on basic and oauth1.
my credentials are also 100% correct.
<img width="821" alt="Screenshot 2020-05-18 at 7 47 34 PM" src="https://user-images.githubusercontent.com/65539040/82223593-7948eb00-9940-11ea-85f2-981c0ef9534e.png">
this is wp-json api response.

**Comment by vedanshujain** [comment]
This issue is because instead of user name and password, query string params `consumer_key` and `consumer_secret` should be used like, so URL looks like `wp-json/wc/v2/products?consumer_key=xxxx&consumer_secret=xxxx`.

I am closing this issue since we have been a bit late in replying, and likley you would have already solved it or moved on from this problem. But feel free to write back if this is not the case.
