### ISSUE TITLE
[feature request] way to access woocommerce rest api internally...

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce-rest-api#20]
Please add a way to access all rest api method without requiring http request like using 'rest api php wrapper'.

Because woocommerce built-in function is not as comprehensive and as complete as rest api. Sometimes we need to make new function just to do what rest api can already do.

Using 'WP_REST_Request' sometimes causes error like issue#18

**Comment by vedanshujain** [comment]
You can already use https://github.com/woocommerce/wc-api-php or directly instantiate controllers' objects and call methods on them. That said, I would still recommend using proper WC functions instead because controllers as of now also do a lot of request logic, so may not be trivial to adapt for direct use.
It's in our long term plan to refactor methods that will called by controller and can be called by custom code as well. However, I am closing this issue because it's not something we will target in one go, but will happen organically over time.
