### ISSUE TITLE
API's Response Time

### ISSUE THREAD

**Issue by neerajnegidev** [woocommerce/woocommerce-rest-api#202]
Can we use some Caching technique to make API response faster may be redis.

**Comment by vedanshujain** [comment]
Closing this issue for housekeeping the repo (we will open small issues and PRs with specific details on what to implement etc, instead of a generic one like this). Note that this enhancement is on our radar, see https://github.com/woocommerce/woocommerce/pull/27734 and https://github.com/woocommerce/woocommerce/pull/27735
