### ISSUE TITLE
401 Sorry, you are not allowed to edit this resource.

### ISSUE THREAD

**Issue by hqin2013** [woocommerce/woocommerce-rest-api#204]
Hey,

I tried to use CURL to operate woocommerce, Get is OK, but post/put will get `401 error：Sorry, you are not allowed to edit this resource.
`
The same key/secret work for the PHP  code, I can modify the data in WooCommerce.

tried to modify .htaccess file to allow HTTP author, but no effect.

any help?!

Regards
Qin

**Comment by vedanshujain** [comment]
[REST API PHP App](https://github.com/woocommerce/wc-api-php) uses the same REST API internally, so if a key works in the app, then it should work in API natively as well. I am closing this issue for general repo maintainence, since we were not able to respond in time it's likely that you would have solved or moved on from this problem.

If you are still facing this problem, can you please open an issue in [WooCommerce core repo](https://github.com/woocommerce/woocommerce) with following details:
1. [System status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/).
2. Exact request and response data.
