### ISSUE TITLE
Allow setting and modification of user roles

### ISSUE THREAD

**Issue by rkbjunior** [woocommerce/woocommerce-rest-api#210]
The WordPress API allows setting/updating user roles, but the woocommerce rest api has the roles field as read only. 

I suggest that the woocommerce rest api be modified to allow the the user roles field to be set/updated.

**Comment by vedanshujain** [comment]
This enhancement is likely not needed because:
1. WooCommerce API is mostly limited to creating/updating users with customer role, and adding any role is likely out of scope of an eCommerce plugin.
2. This functionality is already provided by WP core API with all permission checks and everything in between. There is no need to implement again what is already there.

I am closing this issue, but feel free to comment back if you want to dicuss further.

**Comment by rkbjunior** [comment]
Woocommerce only adds the one customer role, but their are plenty of plugins that allow the creation of custom user roles. Many of which could describe a customer. My company is a valid use case where e commerce customers are broken up into several roles. So I would tend to disagree with the sentiment that adding additional roles is outside of the scope of an ecommerce plugin. 

That aside, I've also come across a scenario where the api does not assign a customer IP for orders placed in via the rest api. The customer_ip field is also read only. Unfortunately I have a fraud detection plugin that will not validate an order unless the customer_ip field is set. I've contacted the developers and they basically told me they cant validate without an IP. Which seems silly to me, but my hands are tied, I cant make developers change their software just for me. I understand that...  So....

Is there a way to extend the woocommerce rest api so I can set these fields (customer role, customer_ip) as read/write? What other suggestions might you have to overcome these obstacles?
