### ISSUE TITLE
api woocomerce woocommerce_rest_authentication_error

### ISSUE THREAD

**Issue by AngelT91** [woocommerce/woocommerce-rest-api#213]
Hello how are you?

I hope you can help me I am having problems trying to use the api woocomerce, when I want to make a query about my products I get this error

http://papeleriazaragoza.mx/img/img-1.png

http://papeleriazaragoza.mx/img/img-2.png

I already tried the following settings in the .htaccess file

<IfModule mod_rewrite.c>
#METALOCATOR: This line added to allow basic authentication under FastCGI
SetEnvIf Authorization “(.*)” HTTP_AUTHORIZATION=$1

RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ – [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]

#METALOCATOR: This line added to allow basic authentication under FastCGI
#METALOCATOR: Establishes an environment variable used by the plugin only for URLs beginning with wp-json/
RewriteRule ^wp-json/.* – [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
</IfModule>
#END WordPress

what do you recommend me to do

**Comment by vedanshujain** [comment]
From your site, it looks like it has automatic redirection from `http` to `https` enabled, and I suspect that this is causing a problem since in your client when generating a signature, URL is considered as `http://papeleriazaragoza.mx` but in the server when comparing, it becomes `https://papeleriazaragoza.mx`. So basically the signature will become invalid.

It should work fine if you use `https` instead from the get-go in your client or disable automatic request upgrade (I would prefer former instead of latter). For comparison, this my working request screenshot:

<img width="608" alt="Screenshot 2020-10-26 at 5 19 24 PM" src="https://user-images.githubusercontent.com/7571618/97169197-ab902b80-17af-11eb-9fd6-13ab30d7c9bc.png">


I am closing this issue now as part of general maintainence, but feel free to comment back if you have more questions.
