### ISSUE TITLE
List all completed orders using Before and After date-time parameter?

### ISSUE THREAD

**Issue by ivandjordjevic** [woocommerce/woocommerce-rest-api#217]
We do have a requirement  to get all orders from woocommerce that are in status Completed. To avoid getting the full list of all completed orders with each HTTP request, out Get requests are always using Before/After parameters. Idea is that with each request to only get the list of new completed orders from the last call.

Example is that with first call at [SyncDateTime] I'm getting orders with ids 1,2,3. When I'm creating a new call for 'orders' I'm using After parameter with [SyncDateTime] to only get orders 4,5 (but not 1,2 and 3 because they are already synced with our software).

But with this approach we might miss orders that are recently updated to complete status because changing the status of an order won't make that order fall into before/after time frame since those dates are only related to when the order is created.

How do you get across that challenge to only pull new completed orders from the last call?

**Comment by ivandjordjevic** [comment]
Any ideas?

**Comment by vedanshujain** [comment]
You can use the `date_column` param to track the recently updated order. For example, your API rquest will now become:
`wp-json/wc/v3/orders?after=[SyncDateTime]&date_column=modified`. 

Note that only meta data updates will not be captured because date_modified is only changed when the original order object is changed. However this will capture recently completed orders better than using just the `after` parameter.

That said, we are looking at adding a fancier and more complete sync functionality using REST API, but it's too early at this point to say if/when it will be picked up or get implemented.

I am closing this issue as part of general repo maintainence, but feel free to comment back if you have any questions.
