### ISSUE TITLE
Unable to DELETE product using REST api v3

### ISSUE THREAD

**Issue by thearyanahmed** [woocommerce/woocommerce-rest-api#235]
Here is my code
```php
public function deleteProduct($id)
{
     # client is  Automattic\WooCommerce\Client;
     return $this->client->delete('products/' . $id, ['force' => true]);
}
```

I receive `JSON ERROR` *vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php* on line 375. 

I've dumped the response 

![image](https://user-images.githubusercontent.com/20617352/89877179-88f36b00-dbe1-11ea-99be-7c1132b3518b.png)

It's text/html. Using the official woocommerce-rest-api. Following the docs from [woocommerce-rest-api-docs](https://woocommerce.github.io/woocommerce-rest-api-docs/#delete-a-product)
 
how can I solve this problem?

**Comment by vedanshujain** [comment]
Looks like this issue is happening because of the NGINX configuration on your server, instead of WooCommerce itself. This response is clearly returned by the NGINX server (we don't have this message anywhere in the app as far as I can see). Perhaps it's configured to not allow `DELETE` request by default? I have seen this type of issue in some servers when NGINX rules are misconfigured in that it thinks this is a webdav request instead of a normal HTTP method request. Maybe config llike this is needed:
```
 location / {
                try_files $uri $uri/ /index.php?$args;
        }
```

I would recommend that you check if DELETE requests on other non woocommerce endpoints are working, for example in core WordPress API. Without looking at your exact server configuration I cannot point out what's wrong.

That said, I also tried out your exact code on my local setup and it was working as expected, see

![Screenshot 2020-10-27 at 2 02 06 PM](https://user-images.githubusercontent.com/7571618/97276354-13508000-185d-11eb-9123-2aefa0cfd2ba.png)


I am closing this issue because as of now it looks unrelated to WooCommerce core, but feel free to comment back if you have more questions/feedback.
