### ISSUE TITLE
Add notes and balance per customer in admin and REST API

### ISSUE THREAD

**Issue by amirvenus** [woocommerce/woocommerce-rest-api#51]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to use third-party buggy plugins to integrate WooCommerce with the CRMs I create in C#. 

Most of the user-cases involve accessing customer notes and balance which is not available in WooCommerce out of the box. 

**Describe the solution you'd like**

Two new fields in Customer properties REST API object:

string notes
decimal balance

**Describe alternatives you've considered**
Using third-party plugins that do not have good or any integration with the REST API.

**Comment by claudiosanches** [comment]
By default both are not part of WooCommerce core, so it's not correct to just include both in the REST API, but this is also seems like a specific case, plugins for it should integrate better, this isn't direct a problem for WooCommerce, also you can extend the endpoint to include any field you want, even it's possible to create your own WordPress REST API endpoint ready for your CRM, so you just query and return the data required for the CRM.
I'll close for now since it's out of WooCommerce scope those fields for now, but we can revise this idea in the future in case we include some CRM functionality to WooCommerce, something that I personally like to see one day.
