### ISSUE TITLE
Remove read-only from customer role in REST API

### ISSUE THREAD

**Issue by amirvenus** [woocommerce/woocommerce-rest-api#52]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to create a customer using the REST API and then having to change its role as the WC one is read-only. 

**Describe the solution you'd like**
Remove read-only from Customer-> role in the REST API

**Describe alternatives you've considered**
For now, I have to either modify the database to change the customer's role or use the Wordpress's API to do so. 

Alternatively, the role can be changed using the WC Admin page and I wonder why it's read-only on the API!

**Comment by claudiosanches** [comment]
>  For now, I have to either modify the database to change the customer's role or use the Wordpress's API to do so.

Those aren't the only options, there's filters to enable it.
You can find all functions and filters to change it in:

https://github.com/woocommerce/woocommerce/blob/81360d682764658c9fa5e79c795b0cb4ccf93967/includes/wc-rest-functions.php#L214-L353

Closing because for now we don't plan to open the REST API for everyone, since this may cause security problems for some people.
