### ISSUE TITLE
Woocommerce api add to cart

### ISSUE THREAD

**Issue by huykon** [woocommerce/woocommerce-rest-api#58]
Hi everyone!
I am looking for the way I can add to cart via Woo API, I didn't find it from woocommerce api doc . Probably there is not thing in there so can supporter or someone know the way to get it? 
Thanks!

**Comment by juliaamosova** [comment]
@huykon adding to cart via WooCommerce REST API is currently not possible. 

You can try using [Cart REST API for WooCommerce – CoCart Lite](https://wordpress.org/plugins/cart-rest-api-for-woocommerce/) plugin. 

For the reference, also see https://github.com/woocommerce/woocommerce/issues/8909. 

Closing this issue since no action to be taken at the moment.
