### ISSUE TITLE
product_id being mandatory when PUT'ing via REST.

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce-rest-api#61]
**Describe the bug**
Can't seem to update order lines via REST unless a product id is supplied. I don't believe it was always like this, and the docs at http://woocommerce.github.io/woocommerce-rest-api-docs/#order-line-items-properties does not mention it being mandatory.

If I PUT this to `/wp-json/wc/v3/orders/1545?dp=2`:
```
{
    "line_items": [
        {
            "id": 287,
            "subtotal": "52.00"
        }
    ]
}
```

I get an HTTP 400 back:
```
{
    "code": "woocommerce_rest_required_product_reference",
    "message": "Product ID or SKU is required.",
    "data": {
        "status": 400
    }
}
```

**Expected behavior**
I expect being able to update existing order lines without supplying the product id. And in fact, I would expect to be able to create new order lines without a product id as well.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Thanks for opening the issue @larssn. I can reproduce the behavior you are describing. 

Currently, regardless of how many products are in the order, product ID or SKU is required in order to update `line_items`. 

**GET Request for the order #191 details:**

![get1](https://user-images.githubusercontent.com/19143190/70991824-37312a00-20c0-11ea-9df6-03db594524eb.jpg)

**PUT Request to update `line_items` `subtotal` of a product in order #191 with `product_id` provided - as a result, the subtotal is updated:**

![get2](https://user-images.githubusercontent.com/19143190/70991907-6778c880-20c0-11ea-99e2-96b158b944e3.jpg)

**PUT Request to update `line_items` `subtotal` of a product in order #191 with `product_id` not provided - as a result, we are getting an error message asking for product id or sku:**

![get3](https://user-images.githubusercontent.com/19143190/70991969-9131ef80-20c0-11ea-93a4-e5d20077fd32.jpg)

**Comment by larssn** [comment]
Thanks for replying Julia, it's just strange it's like that.

The line item id should uniquely identify that order item, so it's puzzling why sku and product id would be required, agree?

**Comment by claudiosanches** [comment]
>  I expect being able to update existing order lines without supplying the product id. And in fact, I would expect to be able to create new order lines without a product id as well.

This has been always mandatory, at least in our current REST API v2 and v3.

I agree that for updating should not be necessary, still for create is mandatory for sure.
Also you may use `sku`, `product_id` or `variation_id` in order to get the correct product, so at least one of those values is mandatory while creating a line item.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #79.

**Comment by larssn** [comment]
@claudiosanches Thanks for the help Claudio!

The reason I kinda expected being able to create order lines without a product id, is when I consider the scenario where an order has an order-line tied to a product, and then that product is deleted. That order line's product_id then points to nothing.

Since that is already supported, I figured you might support the same via REST.

The actual use case where this is relevant for is that I need to do a legacy import of a bunch of orders from an old WC installation to a new installation via REST, where I don't have access to the original products those orders were based on. And even if I had access to them, the customer is not interested in those old products in the new WC installation.
