### ISSUE TITLE
[Orders] $request param mis-usage

### ISSUE THREAD

**Issue by liviudobrea** [woocommerce/woocommerce-rest-api#64]
Could someone please explain to me how does this work ?

https://github.com/woocommerce/woocommerce-rest-api/blob/390fb8142078999d667fe8342bc3eec6496958e1/src/Controllers/Version3/class-wc-rest-orders-controller.php#L73-L122

![image](https://user-images.githubusercontent.com/7279288/68886995-7c0c1e80-0718-11ea-9aeb-3f64ec023b35.png)

The above snapshot is triggered via a postman request.

**! HOWEVER**, when sending this request via the woocommerce nodejs api (which sends the request body as i do from postman) it somehow works.

L.E. a bit of context in case it is not clear what's happening. In the above method (`prepare_object_for_database`) The **$request** param is marked as **WP_REST_Request** type (which indeed it is), but it is being treated if it were the decoded body of the $request. In V4 this was changed.

**Comment by claudiosanches** [comment]
>L.E. a bit of context in case it is not clear what's happening. In the above method (prepare_object_for_database) The $request param is marked as WP_REST_Request type (which indeed it is), but it is being treated if it were the decoded body of the $request. In V4 this was changed.

Note that [`WP_REST_Request`](https://developer.wordpress.org/reference/classes/wp_rest_request/) implements [PHP `ArrayAccess` class](https://www.php.net/manual/en/class.arrayaccess.php), that's why it's possible to access any data.

Like using `$request['id']` it's the same than using `$request->get_param( 'id' )`.
Note that the same is used in the WordPress REST API endpoints:

https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L953
